# Generated by Django 3.1.5 on 2021-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210415_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='editRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetPost', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
