# Generated by Django 3.1.5 on 2021-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_editrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
