# Generated by Django 3.1.5 on 2021-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_editrequest_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editrequest',
            name='read',
        ),
        migrations.AddField(
            model_name='incident',
            name='beingEdited',
            field=models.BooleanField(default=False),
        ),
    ]
